#!/bin/bash
function process_running {
  if pgrep -x "$1" &> /dev/null; then
	  return 0
  else
	  return 1
  fi
}
function process_start {
  process_name=$1
  echo "Process $process_name is not running. Attempting to restart"

  if sudo systemctl $process_name start; then
	  echo "process $process_name restarted successfully"
  else
	  echo "Restart failed"
  fi
}

if [[ $# -eq 0  ]]; then
	echo "$0 <program name>"
	exit 1
fi

program_name="$1"
max_attempt=3
attempt=1
while [ $attempt -le $max_attempt ]; do
	if process_running "$program_name"; then
		echo "Process is already running"
	else
		process_start $program_name
	fi
	attempt=$((attempt+1))
	sleep 5
done

echo "Max attempts reached"
